// Copyright (c) 2009-2010 Simon Fell
//
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
// THE SOFTWARE.
//
// 
// Note: This file was generated by WSDL2ZKSforce. 
//		  see https://github.com/superfell/WSDL2ZKSforce
//       DO NOT HAND EDIT.
//

#import "zkXmlDeserializer.h"

/*
<complexType name="DescribeGlobalSObjectResult" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:tns="urn:partner.soap.sforce.com" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <sequence>
    <element type="xsd:boolean" name="activateable"/>
    <element type="xsd:boolean" name="createable"/>
    <element type="xsd:boolean" name="custom"/>
    <element type="xsd:boolean" name="customSetting"/>
    <element type="xsd:boolean" name="deletable"/>
    <element type="xsd:boolean" name="deprecatedAndHidden"/>
    <element type="xsd:boolean" name="feedEnabled"/>
    <element type="xsd:boolean" name="idEnabled"/>
    <element nillable="true" type="xsd:string" name="keyPrefix"/>
    <element type="xsd:string" name="label"/>
    <element type="xsd:string" name="labelPlural"/>
    <element type="xsd:boolean" name="layoutable"/>
    <element type="xsd:boolean" name="mergeable"/>
    <element type="xsd:boolean" name="mruEnabled"/>
    <element type="xsd:string" name="name"/>
    <element type="xsd:boolean" name="queryable"/>
    <element type="xsd:boolean" name="replicateable"/>
    <element type="xsd:boolean" name="retrieveable"/>
    <element type="xsd:boolean" name="searchable"/>
    <element type="xsd:boolean" name="triggerable"/>
    <element type="xsd:boolean" name="undeletable"/>
    <element type="xsd:boolean" name="updateable"/>
  </sequence>
</complexType>
*/
@interface ZKDescribeGlobalSObject : ZKXmlDeserializer {
}
@property (readonly) BOOL       activateable; 
@property (readonly) BOOL       createable; 
@property (readonly) BOOL       custom; 
@property (readonly) BOOL       customSetting; 
@property (readonly) BOOL       deletable; 
@property (readonly) BOOL       deprecatedAndHidden; 
@property (readonly) BOOL       feedEnabled; 
@property (readonly) BOOL       idEnabled; 
@property (readonly) NSString  *keyPrefix; 
@property (readonly) NSString  *label; 
@property (readonly) NSString  *labelPlural; 
@property (readonly) BOOL       layoutable; 
@property (readonly) BOOL       mergeable; 
@property (readonly) BOOL       mruEnabled; 
@property (readonly) NSString  *name; 
@property (readonly) BOOL       queryable; 
@property (readonly) BOOL       replicateable; 
@property (readonly) BOOL       retrieveable; 
@property (readonly) BOOL       searchable; 
@property (readonly) BOOL       triggerable; 
@property (readonly) BOOL       undeletable; 
@property (readonly) BOOL       updateable; 
@end
