// Copyright (c) 2013 Simon Fell
//
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
// THE SOFTWARE.
//
// 
// Note: This file was generated by WSDL2ZKSforce. 
//		  see https://github.com/superfell/WSDL2ZKSforce
//       DO NOT HAND EDIT.
//

#import "ZKMassEmailMessage.h"
#import "zkEnvelope.h"

@implementation ZKMassEmailMessage

@synthesize description, targetObjectIds, templateId, whatIds;

-(void)dealloc {
	[description release];
	[targetObjectIds release];
	[templateId release];
	[whatIds release];
	[super dealloc];
}

-(void)serializeToEnvelope:(ZKEnvelope *)env elemName:(NSString *)elemName {
	[env startElement:elemName type:@"MassEmailMessage"];
	[env addBoolElement:@"bccSender"        elemValue:self.bccSender];
	[env addElement:@"emailPriority"        elemValue:self.emailPriority     nillable:YES optional:NO];
	[env addElement:@"replyTo"              elemValue:self.replyTo           nillable:YES optional:NO];
	[env addBoolElement:@"saveAsActivity"   elemValue:self.saveAsActivity];
	[env addElement:@"senderDisplayName"    elemValue:self.senderDisplayName nillable:YES optional:NO];
	[env addElement:@"subject"              elemValue:self.subject           nillable:YES optional:NO];
	[env addBoolElement:@"useSignature"     elemValue:self.useSignature];
	[env addElement:@"description"          elemValue:self.description       nillable:YES optional:NO];
	[env addElementArray:@"targetObjectIds" elemValue:self.targetObjectIds];
	[env addElement:@"templateId"           elemValue:self.templateId        nillable:NO  optional:NO];
	[env addElementArray:@"whatIds"         elemValue:self.whatIds];
	[env endElement:elemName];
}
@end
