// Copyright (c) 2013 Simon Fell
//
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
// THE SOFTWARE.
//
// 
// Note: This file was generated by WSDL2ZKSforce. 
//		  see https://github.com/superfell/WSDL2ZKSforce
//       DO NOT HAND EDIT.
//

#import "ZKProcessSubmitRequest.h"
#import "zkEnvelope.h"

@implementation ZKProcessSubmitRequest

@synthesize objectId, submitterId, processDefinitionNameOrId, skipEntryCriteria;

-(void)dealloc {
	[objectId release];
	[submitterId release];
	[processDefinitionNameOrId release];
	[super dealloc];
}

-(void)serializeToEnvelope:(ZKEnvelope *)env elemName:(NSString *)elemName {
	[env startElement:elemName type:@"ProcessSubmitRequest"];
	[env addElement:@"comments"                  elemValue:self.comments                  nillable:YES optional:NO];
	[env addElementArray:@"nextApproverIds"      elemValue:self.nextApproverIds];
	[env addElement:@"objectId"                  elemValue:self.objectId                  nillable:NO  optional:NO];
	[env addElement:@"submitterId"               elemValue:self.submitterId               nillable:YES optional:NO];
	[env addElement:@"processDefinitionNameOrId" elemValue:self.processDefinitionNameOrId nillable:YES optional:NO];
	[env addBoolElement:@"skipEntryCriteria"     elemValue:self.skipEntryCriteria];
	[env endElement:elemName];
}
@end
