// Copyright (c) 2006,2011 Simon Fell
//
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
// THE SOFTWARE.
//

#import "zkSforceClient.h"
#import "zkSObject.h"
#import "zkSoapException.h"
#import "ZKDescribeQuickActionResult.h"
#import "ZKDescribeDataCategoryGroupResult.h"
#import "ZKGetDeletedResult.h"
#import "ZKMergeResult.h"
#import "ZKDescribeColor.h"
#import "ZKLoginResult.h"
#import "ZKDeleteResult.h"
#import "ZKSetPasswordResult.h"
#import "ZKEmptyRecycleBinResult.h"
#import "ZKDescribeComponentInstanceProperty.h"
#import "ZKDeletedRecord.h"
#import "ZKPerformQuickActionRequest.h"
#import "ZKDescribeQuickActionListItemResult.h"
#import "ZKDescribeSoftphoneScreenPopOption.h"
#import "ZKDescribeGlobalResult.h"
#import "ZKLeadConvert.h"
#import "ZKDescribeSoftphoneLayoutItem.h"
#import "ZKDescribeSoftphoneLayoutResult.h"
#import "ZKDescribeQuickActionDefaultValue.h"
#import "ZKDescribeLayout.h"
#import "ZKChildRelationship.h"
#import "ZKDescribeGlobalSObjectResult.h"
#import "ZKEmail.h"
#import "ZKRelatedListColumn.h"
#import "ZKDescribeTabSetResult.h"
#import "ZKResetPasswordResult.h"
#import "ZKDescribeLayoutComponent.h"
#import "ZKDescribeIcon.h"
#import "ZKDescribeLayoutItem.h"
#import "ZKDescribeAppMenuResult.h"
#import "ZKUndeleteResult.h"
#import "ZKRecordTypeMapping.h"
#import "ZKSaveResult.h"
#import "ZKInvalidateSessionsResult.h"
#import "ZKDescribeCompactLayout.h"
#import "ZKDescribeDataCategoryGroupStructureResult.h"
#import "ZKPicklistEntry.h"
#import "ZKUpsertResult.h"
#import "ZKDescribeSoftphoneLayoutCallType.h"
#import "ZKSearchResult.h"
#import "ZKDescribeRelatedContentItem.h"
#import "ZKDescribeAvailableQuickActionResult.h"
#import "ZKSendEmailResult.h"
#import "ZKGetServerTimestampResult.h"
#import "ZKGetUpdatedResult.h"
#import "ZKProcessResult.h"
#import "ZKDescribeLayoutSection.h"
#import "ZKPerformQuickActionResult.h"
#import "ZKRecordTypeInfo.h"
#import "ZKDataCategoryGroupSobjectTypePair.h"
#import "ZKRelatedList.h"
#import "ZKProcessRequest.h"
#import "ZKPicklistForRecordType.h"
#import "ZKDescribeFlexiPageResult.h"
#import "ZKDescribeFlexiPageRegion.h"
#import "ZKDescribeSObjectResult.h"
#import "ZKRecordTypeCompactLayoutMapping.h"
#import "ZKDescribeQuickActionListResult.h"
#import "ZKSearchRecord.h"
#import "ZKDescribeAppMenuItem.h"
#import "ZKDescribeComponentInstance.h"
#import "ZKDescribeLayoutButtonSection.h"
#import "ZKDescribeSearchLayoutResult.h"
#import "ZKDescribeColumn.h"
#import "ZKMergeRequest.h"
#import "ZKDescribeSoftphoneLayoutInfoField.h"
#import "ZKDescribeSearchScopeOrderResult.h"
#import "ZKDescribeTab.h"
#import "ZKError.h"
#import "ZKUserInfo.h"
#import "ZKRelatedContent.h"
#import "ZKDescribeThemeResult.h"
#import "ZKDescribeLayoutResult.h"
#import "ZKDescribeLayoutRow.h"
#import "ZKDescribeLayoutButton.h"
#import "ZKRelatedListSort.h"
#import "ZKSendEmailError.h"
#import "ZKDescribeCompactLayoutsResult.h"
#import "ZKDescribeSoftphoneLayoutSection.h"
#import "ZKDescribeGlobalTheme.h"
#import "ZKDescribeThemeItem.h"
#import "ZKLeadConvertResult.h"
#import "ZKDescribeField.h"
#import "ZKDataCategory.h"
#import "ZKDescribeField+Extras.h"
#import "zkQueryResult+NSTableView.h"
#import "ZKRelatedList+Extras.h"
#import "ZKSaveResult+Extras.h"
#import "zkSforceClient+zkAsyncQuery.h"
#import "ZKUserInfo+Extras.h"
